name: Thumbnail - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy Env's
        run: cp build/ci/.env-test-example build/ci/.env

      - name: Run docker
        run: docker-compose -f build/ci/docker-compose-ci.yml up -d --build

      - name: Install dependencies
        run: docker exec thumbnail-app sh -c "go mod download && go mod verify"

      - name: Run test
        run: docker exec -u dev thumbnail-app sh -c "go test ./... -cover -v -coverprofile cover.out"

      - name: Coverage
        run: docker exec thumbnail-app bash build/ci/cover.sh
